Milestone 2
jaspreet-singh-sahota/react-bookstore pull request #2
Opened 2020-09-17 13:48 UTC by OdongAlican

# This is milestone2 of the React Bookstore project.
## In this milestone, we did the following:-

- Created components and containers directories in the src
- Created an actions directory with the index.js
- Created a reducers directory with two files: books.js and index.js
- Added BooksList and BooksForm in the App component
- Update BooksList, Book, and BooksForm components

2020-09-17 15:42 UTC, suretrust requested changes
Hi team, 👋 

### Great job thus far! 🙌 Please see my comments. 👇 

- [ ] The `App` component should be placed in `src/components` directory.
- [ ] The `Book` component should be placed in `src/components` directory.
- [ ] The `BookList` component should be placed in `src/containers` directory.
- [ ] The `BookForm` component should be placed in `src/containers` directory.

**Note:** Any component that connects to the store should be placed in the `containers` directory.

**KIndly submit another CRR once these issues have been solved.** _Happy coding!_ 🎉

2020-09-17 15:42 UTC, suretrust commented on src/index.js
> +  book: [
Perhaps, it would be better if this is plural?
```suggestion
  books: [
```

2020-09-17 17:43 UTC, Oghenebrume50 approved these changes
### APPROVED

Hi @OdongAlican good job you have done so far, kudos for making changes as earlier requested, this looks good to me :+1: 
Please merge and move on, **This is approved** :slightly_smiling_face: 

**RAPHAEL NORIODE** :mask: STAY_SAFE

2020-09-17 18:23 UTC, merged

2020-09-18 14:09 UTC, jaspreet-singh-sahota commented
hi, @suretrust @Oghenebrume50,

Thank you for the review and for approving the code.

best regards,
Jaspreet Singh